// Project info

name := "play-mongojack"

organization := "org.mongojack"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.11.1"

resolvers ++= Seq(
	 "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"
)


// Dependencies

libraryDependencies ++= Seq(
    "org.mongojack" % "mongojack" % "2.3.0",
    "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.5.1"
)

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2" % "2.4.16" % "test"
)

// Configuration required for deploying to sonatype

publishMavenStyle := true

publishTo <<= version { (v: String) =>
  val nexus = "https://oss.sonatype.org/"
  if (v.trim.endsWith("SNAPSHOT"))
    Some("snapshots" at nexus + "content/repositories/snapshots")
  else
    Some("releases"  at nexus + "service/local/staging/deploy/maven2")
}

pomIncludeRepository := { _ => false }

publishArtifact in Test := false

lazy val root = (project in file(".")).enablePlugins(PlayScala).settings(
	sbt.Keys.fork in Test := false
)


pomExtra := (
  <url>http://github.com/jroper/play-mongojack</url>
  <inceptionYear>2012</inceptionYear>
  <licenses>
    <license>
      <name>Apache 2</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
      <comments>A business-friendly OSS license</comments>
    </license>
  </licenses>
  <scm>
    <url>git@github.com:jroper/play-mongojack.git</url>
    <connection>scm:git:git@github.com:jroper/play-mongojack.git</connection>
  </scm>
  <developers>
    <developer>
      <name>James Roper</name>
      <email>james@jazzy.id.au</email>
      <url>http://jazzy.id.au</url>
      <roles>
        <role>Author</role>
      </roles>
      <organization>Typesafe</organization>
    </developer>
  </developers>)
